const products = [
    {
      id: 1,
      name: "Living Room Sets",
      price: 1520.0,
      oldPrice: 1540.0,
      imgSrc: "../../images/section3/img1.jpg",
      alt: "Living Room Set",
    },
    {
      id: 2,
      name: "Sofa for Living Room",
      price: 1520.0,
      oldPrice: 1540.0,
      imgSrc: "../../images/section3/img2.jpg",
      alt: "Sofa for Living Room",
      discount:"-15%",
    },
    {
      id: 3,
      name: "Living Room Sets",
      price: 1520.0,
      oldPrice: 1540.0,
      imgSrc: "../../images/section3/img3.jpg",
      alt: "Living Room Set",
      discount:"-10%",
    },
    {
      id: 4,
      name: "product with video",
      price: 1520.0,
      oldPrice: 1540.0,
      imgSrc: "../../images/section3/img4.jpg",
      alt: "Living Room Set",
    },
    {
      id: 5,
      name: "Unique content for each",
      price: 855.0,
      oldPrice: 1000.0,
      imgSrc: "../../images/section3/img5.jpg",
      alt: "Living Room Set",
      discount:"-11%",
    },
    {
      id: 6,
      name: "new badge product",
      price: 10.0,
      oldPrice: 154.0,
      imgSrc: "../../images/section3/img6.jpg",
      alt: "Living Room Set",
    },
    {
      id: 7,
      name: "variable product",
      price: 124.0,
      oldPrice: 1540.0,
      imgSrc: "../../images/section3/img7.jpg",
      alt: "Living Room Set",
      discount:"-18%",
    },
    {
      id: 8,
      name: "soldout product",
      price: 20.0,
      oldPrice: 200.0,
      imgSrc: "../../images/section3/img8.jpg",
      alt: "Living Room Set",
      discount:"-34%",
    },

    {
      id: 1,
      name: "Living Room Sets",
      price: 152.0,
      oldPrice: 154.0,
      imgSrc: "../../images/section3/img1.jpg",
      alt: "Living Room Set",
    },
    {
      id: 2,
      name: "Sofa for Living Room",
      price: 120.0,
      oldPrice: 140.0,
      imgSrc: "../../images/section3/img2.jpg",
      alt: "Sofa for Living Room",
      discount:"-15%",
    },
    {
      id: 3,
      name: "Living Room Sets",
      price: 150.0,
      oldPrice: 150.0,
      imgSrc: "../../images/section3/img3.jpg",
      alt: "Living Room Set",
      discount:"-10%",
    },
    {
      id: 4,
      name: "product with video",
      price: 520.0,
      oldPrice: 540.0,
      imgSrc: "../../images/section3/img4.jpg",
      alt: "Living Room Set",
    },
    {
      id: 5,
      name: "Unique content for each",
      price: 55.0,
      oldPrice: 100.0,
      imgSrc: "../../images/section3/img5.jpg",
      alt: "Living Room Set",
      discount:"-11%",
    },
    {
      id: 6,
      name: "new badge product",
      price: 10.0,
      oldPrice: 15.0,
      imgSrc: "../../images/section3/img6.jpg",
      alt: "Living Room Set",
    },
    {
      id: 7,
      name: "variable product",
      price: 124.0,
      oldPrice: 540.0,
      imgSrc: "../../images/section3/img7.jpg",
      alt: "Living Room Set",
      discount:"-18%",
    },
    {
      id: 8,
      name: "soldout product",
      price: 20.0,
      oldPrice: 200.0,
      imgSrc: "../../images/section3/img8.jpg",
      alt: "Living Room Set",
      discount:"-34%",
    },
  ];

export default products;